### ISSUE TITLE
Add option to warn if all children don't link to every parent

### ISSUE THREAD

**Issue by robertberrington** [jacebrowning/doorstop#141]
In "light" requirements, children only link to parents where necessary. However, in a formal requirements setting, you might consider forcing all children to link to parents, even if it is a placeholder justifying why the parent does NOT impact the child.

**Comment by michaelnt** [comment]
For instance in the requirements for doorstop the children of REQ are TUT and LLT, every REQ must be linked from either TUT OR LLT but there is no warning for items that aren't linked from BOTH.

WARNING: REQ: REQ001: no links from document: TUT
WARNING: REQ: REQ016: no links from document: LLT
WARNING: REQ: REQ017: no links from document: LLT
WARNING: REQ: REQ008: no links from document: TUT
WARNING: REQ: REQ009: no links from document: TUT
WARNING: REQ: REQ014: no links from document: TUT
WARNING: REQ: REQ015: no links from document: TUT

**Comment by jacebrowning** [comment]
This feature is now available for testing using the --strict-child-check` option with `Doorstop==1.1b1`.
