### ISSUE TITLE
Add document ignore option to static analysis

### ISSUE THREAD

**Issue by robertberrington** [jacebrowning/doorstop#179]
When I'm in the process of developing a new document, I'd like to suppress `ERROR` and `WARNING` so I can see when real content changes.

This would allow new content to be merged onto existing development without causing CI grief due to the new content.

`$ doorstop --ignore-doc CM-SWHLT`

**Comment by jacebrowning** [comment]
This is a duplicate of https://github.com/jacebrowning/doorstop/issues/191, which has a much better description of the feature request.
