### ISSUE TITLE
Add option to suppress messages for selected documents

### ISSUE THREAD

**Issue by robertberrington** [jacebrowning/doorstop#191]
We're developing multiple documents/levels and are transitioning certain ones under formal change control.

It would be helpful if we could run the `doorstop` validation, but suppress the `ERROR`|`WARNING`|`INFO` for select documents.

Example:

```
Feature List [FL]
  |
  -- System Requirements Specification [SYSRS]
    |
    ---- Software High-Level Requirements [SWHLR]
    |
    ---- Hardware High-Level Requirements [HWHLR]
```

The `FL` and `SYSRS` are reviewed and approved by the customer. Work is beginning on `SWHLR` and `HWHLR`. We need to track/fix `FL`|`SYSRS`, but `SWHLR`|`HWHLR` are a little more free-flowing.

I'd like to run `$ doorstop` from my `Makefile` and CI and only generate errors when `FL` and/or `SYSRS` are affected. Also since `FL`|`SYSRS` are held to a higher level of integrity, I'm also elevating `WARNING` -> `ERROR`.

An example command line call could be:
`$ doorstop --no-level-check --error-all --suppress SWHLR --suppress HWHLR`

**Comment by jacebrowning** [comment]
@robertberrington #192 adds a `-s/--skip` option that can be applied multiple times. Does that meet your needs?

**Comment by robertberrington** [comment]
@jacebrowning ... provided feedback in #192. We can close this one if you want.
