### ISSUE TITLE
Fenced markdown is reformatted

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/doorstop#193]
This text should not be reformatted:

``````
```
# A heading
```
``````
##

**Comment by jacebrowning** [comment]
I'm staring to think the "automatic cleanup" of the Markdown is too aggressive. Simply striping leading, trailing, and multiple lines of whitespace might be enough.

**Comment by michaelnt** [comment]
I agree as the current re-formatting prevents using tables, for instance.

I could imagine the re-wrapping of very long lines might be useful when importing from excel, where it is, a little more, difficult to insert new lines.

**Comment by jacebrowning** [comment]
If you have time, I would appreciate a PR that limits cleanup to striping leading, trailing, and multiple lines of whitespace.

**Comment by michaelnt** [comment]
I'll take a look at that, should be a useful step along the way to getting tables supported

**Comment by jacebrowning** [comment]
And probably supersedes https://github.com/jacebrowning/doorstop/pull/208.

**Comment by michaelnt** [comment]
Likely that the checksums will change marking requirements as unreviewed
and suspect. Not sure what can easily be done about that

**Comment by jacebrowning** [comment]
People will need to run `doorstop review all` after updating.

**Comment by jacebrowning** [comment]
Please test this in `Doorstop==1.2b1`.

**Comment by michaelnt** [comment]
Seems that running doorstop to verify links is re-writing the requirements as a string in the yaml file, e.g.
```
text: |
  Some
  text
```
becomes
```
text: "Some\ntext"
```

Still happens when the option -F is set, as doorstop is marking the item as reviewed.

I think its a problem with the way pyaml treats spaces at the end of new lines

**Comment by jacebrowning** [comment]
So this is fixed by https://github.com/jacebrowning/doorstop/pull/215 in `Doorstop==1.2b2`?
