### ISSUE TITLE
Basic usage: missing steps to setup version control

### ISSUE THREAD

**Issue by albertogomcas** [jacebrowning/doorstop#198]
I have been trying to test run doorstop, but after every command I get
> ERROR: no working copy found from: mytestdirectory

I see in the documentation that I am probably missing an important step:
> After configuring version control, a new parent document can be created

But I have no clue how to configure the vcs with doorstep.

**Comment by jacebrowning** [comment]
@albertogomcas What version control system do you plan to use? Currently Doorstop, supports gets its VCS support from the plugins listed here: https://github.com/jacebrowning/doorstop/tree/develop/doorstop/core/vcs

**Comment by albertogomcas** [comment]
I am using SVN (Tortoise client in windows). I have the command line tools installed so the svn command is available in the console.

Once I saw the code you linked I realized it was expecting to find a .svn. I created an empty folder in the repository and checked out a working copy of it (empty except for a .svn subfolder). After that, it worked.

Thanks. On to test it now.

**Comment by jacebrowning** [comment]
Great! Let me know how it goes.

Would it help if the docs say:

> After checking out a new working tree, ...

**Comment by albertogomcas** [comment]
The problem with saying that is that both version control and doorstop talk about 'trees', so it could be interpreted as if you need to have a doorstop skeleton tree in your repository to start with. I would rather put in the docs:

> (OLD) After configuring version control, a new parent document can be created:
> (NEW) A new parent document can be created inside a folder/directory that is under version control:

By the way, the link to the API documentation http://doorstop.info/docs/index.html seems broken.

**Comment by jacebrowning** [comment]
I fixed that broken link. Thanks for pointing it out!
