### ISSUE TITLE
Tables in requirements

### ISSUE THREAD

**Issue by hcw70** [jacebrowning/doorstop#209]
It does not seem to work to have tables in a requirement:

```
  Test some table:
     Yes | no | maybe                     
    -----|----|-----------------------------
     Yes | no | maybe                     
    -----|----|-----------------------------
     Yes | no | maybe                     
```

will be rendered "as is" in html output (ascii art) instead of a html table.
##

**Comment by jacebrowning** [comment]
@michaelnt started a PR to add this feature: https://github.com/jacebrowning/doorstop/pull/208

Feel free to work together of submit your own change with tests to add this feature.

**Comment by michaelnt** [comment]
Tables are now supported see [TUT-017](https://github.com/jacebrowning/doorstop/blob/develop/reqs/tutorial/TUT017.yml), for an example
