### ISSUE TITLE
publish option no-body-levels should also drop levels from headings

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#211]
I have been publishing requirements to markdown and then using pandoc to convert to word. In word I have numbered headings so I want to remove the levels from the published markdown. The option no-body-levels leaves the level markers on the headings.

Should there be a new option that also drops the levels from the headings, or should the existing option be modified?

Perhaps --no-levels=[all|body]

**Comment by jacebrowning** [comment]
I like `--no-levels=[all|body]`.

**Comment by jacebrowning** [comment]
This is available in `Doorstop==1.2b1`.
