### ISSUE TITLE
Don't convert newlines to <\br> when publishing html

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#217]
Lines of text in the yaml file may have been manually wrapped at some column width that doesn't match the column width of the published html, resulting in ugly extra line breaks. Previously I think these lines breaks would have been removed by the sentence boundary re-wrapping code. This behavior doesn't conform to normal markdown and can be worked around by publishing to markdown and then using pandoc to convert to html.

Can we turn off the nl2br option when publishing to html?

**Comment by jacebrowning** [comment]
As long as this doesn't break anything about the way HTML is published, I'm cool with this change.

**Comment by jacebrowning** [comment]
This now available in https://pypi.python.org/pypi/Doorstop/1.2b3.
