### ISSUE TITLE
Reorder drops trailing .0 from level breaking heading titles 

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#219]
The first line of an item will be rendered as a heading if the level ends in .0

The reorder command sometimes strips the trailing .0 changing the heading title to the item ID.

Not sure if it is possible\easy for reorder to determine which lines in index.yml are headings

**Comment by jacebrowning** [comment]
> The reorder command sometimes strips the trailing .0

Are you able to create a consistently failing test case for this? If I were to rebuild this project, I would have made headings explicit rather than inferred from the level. 😄

**Comment by michaelnt** [comment]
I think this occurs because I had no item (to indent) under the heading and the reorder command uses that to detect headings.

I don't think there is anything that can be done here and I should just add an indented item under the heading.
