### ISSUE TITLE
Handling of assets when publishing all documents

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#223]
Currently assets have to have unique names across documents as they all get copied to the same folder when published. Should .doorstop.yml be used to configure the name of the assets folder per document rather than hard coding it to assets for every document?

In the case where multiple documents use assets publishing won't work as the destination assets folder needs to be deleted before copying. Should doorstop copy the contents of the assets folder (rather than the folder itself) to the publish destination.

The use of a relative path names  breaks publishing when there is an assets folder

**Comment by jacebrowning** [comment]
> Should .doorstop.yml be used to configure the name of the assets folder per document rather than hard coding it to assets for every document?

I think the simplest solution would be to manually create uniquely named directories inside existing asset folders and update the image references:

`![Doorstop Logo](assets/logo-black-white.png "Doorstop Logo")` => `![Doorstop Logo](assets/REQ/logo-black-white.png "Doorstop Logo")`

Can you think of a case where this wouldn't work or be too tedious?

> Should doorstop copy the contents of the assets folder (rather than the folder itself) to the publish destination.

Yeah, that makes more sense:

1. Empty the existing published assets directory if it exists
2. Copy files into the assets directory for each document creating subdirectories if needed

> The use of a relative path names breaks publishing when there is an assets folder

I'm thinking that asset paths should always start with `assets/` pointing to an assets directory inside the document directory. Do you have another use case?

**Comment by michaelnt** [comment]
the path to assets should be local but the output path should be expanded to an absolute path as running this publish command fails, at least on windows.

`doorstop publish -m all html`

OK per document assets directory seems unnecessary and makes the publish step simpler

**Comment by jacebrowning** [comment]
> running this publish command fails, at least on windows

How does it fail?

**Comment by michaelnt** [comment]
```shell
publishing to .\HL.md...
Traceback (most recent call last):
  File "c:\anaconda3\lib\distutils\file_util.py", line 35, in _copy_file_contents
    os.unlink(dst)
PermissionError: [WinError 5] Access is denied: '.\\assets\\block_diagram.svg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\doorstop.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\doorstop\cli\main.py", line 96, in main
    success = function(args, os.getcwd(), parser.error)
  File "c:\anaconda3\lib\site-packages\doorstop\cli\commands.py", line 502, in run_publish
    path = publisher.publish(tree, args.path, ext, **kwargs)
  File "c:\anaconda3\lib\site-packages\doorstop\core\publisher.py", line 63, in publish
    common.copy(src, dst)
  File "c:\anaconda3\lib\site-packages\doorstop\common.py", line 189, in copy
    dir_util.copy_tree(src, dst)
  File "c:\anaconda3\lib\distutils\dir_util.py", line 163, in copy_tree
    dry_run=dry_run)
  File "c:\anaconda3\lib\distutils\file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "c:\anaconda3\lib\distutils\file_util.py", line 38, in _copy_file_contents
    "could not delete '%s': %s" % (dst, e.strerror))
distutils.errors.DistutilsFileError: could not delete '.\assets\block_diagram.svg': Access is denied
```

**Comment by michaelnt** [comment]
Running del from the command line works, and it works on linux.

**Comment by jacebrowning** [comment]
Got it. A bugfix for just that issue would be a good start!
