### ISSUE TITLE
template for html publishing

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#225]
I created a html template that places a table of contents in a sidebar, see an example at http://michaelnt.github.io/

I used pandoc to convert the markdown to html and insert a table of contents but doorstop could be modified to use a html template, and optionally add a table of contents.

**Comment by jacebrowning** [comment]
Looks great! 

I think most users would prefer this style over what is currently provided: http://jacebrowning.github.io/doorstop/REQ.html
