### ISSUE TITLE
Javascript front end

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#228]
It would be nice if you could click on an item in a web page, edit it and save the changes to the doorstop server.

Is there an existing Javascript front end for the doorstop server?

I've used the doorstop server to allow multiple people to add new items but I'm not sure what the other views would be used for. Can some of the existing views be modified?

**Comment by jacebrowning** [comment]
That would be really nice to have, but I think such a tool should probably be developed as a separate project that relies on Doorstop as a dependency, similar to these projects:

- https://github.com/nickvanderstel/doorstop-qt
- https://github.com/herrfz/docxreq

There will be lots of interesting problems to solve, like setting version control credentials based on who is using the site, but I think those fall outside the core scope of this repository.

**Comment by michaelnt** [comment]
My plan is that it would be single user and you would still need to run doorstop commands and commit changes manually.

I want to modify doorstop server to add a post method, @post('/documents/<prefix>/items/<uid>') and an option to specify the HTML template used to render @get('/documents/<prefix>').

Ideally I'd like to also modify the index method to link from the tree to the documents as well.

**Comment by jacebrowning** [comment]
I'd accept PRs for that.
