### ISSUE TITLE
Extend re-order command to allow inserts and deletes

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#229]
It would be nice to have an outline mode to create initial headings in a document. It seems like the reorder command, and index.yml, could be extended to support that.

Any thought on what the syntax should be, e.g. lines starting with A# adds a new item and D#TUT001 deletes an item?

**Comment by jacebrowning** [comment]
Deleting an item could be accomplished by simply deleting the item's ID from the outline.

For item addition, the reorder command could treat all unknown IDs as new items and generate the next ID for them, so:

```
outline:
    - REQ018:
        - REQ019:
        - new:
    - new:
```

would add two new items.

**Comment by blastur** [comment]
+1

**Comment by blastur** [comment]
It would be nice if you could also specify if a new item is normative or a heading aswell, for example:

`
outline:
    - REQ018:
        - REQ019:
        - new-heading: This is the new heading text
    - new-item: This is the new item text
`

.. and it would just set level to end with .0 and normative to false on headings, while the new-item tag would work as you suggested.

I think this would greatly simplify building up the skeleton of a document.

**Comment by jacebrowning** [comment]
I like that.

**Comment by michaelnt** [comment]
The changed that was merged marks new items as non normative headings if they have other items indented under them.

I think that is sufficient.
