### ISSUE TITLE
Missing svn command line tools gives confusing error message

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#230]
If the svn command line tools are missing doorstop fails to run, even the publish command, and prints a somewhat cryptic file not found traceback.

TortoiseSVN doesn't install the command line svn tools by default.

**Comment by jacebrowning** [comment]
Perhaps somewhere in [this logic](https://github.com/jacebrowning/doorstop/blob/develop/doorstop/core/vcs/__init__.py), Doorstop should also confirm that the corresponding binary is available.
