### ISSUE TITLE
Problem installing doorstop template assets

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#240]
Tried installing from git on windows and got this error message

`    creating build\lib\doorstop\core\files
    error: can't copy 'doorstop\core\files\assets': doesn't exist or not a regular file`

**Comment by jacebrowning** [comment]
Is this a different problem from https://github.com/jacebrowning/doorstop/pull/239?

**Comment by michaelnt** [comment]
Its probably the same thing, I only tested that fix on linux.

**Comment by jacebrowning** [comment]
@michaelnt Can you still reproduce this with the latest `develop`?

**Comment by michaelnt** [comment]
Thanks, its working now
