### ISSUE TITLE
Fix pylint warnings

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/doorstop#249]
After https://github.com/jacebrowning/doorstop/pull/248, all the remaining pylint warnings seem legitimate to me. Anyone is welcome to chip away at them to get us back to a green build.

Locally, run `$ make pylint` (or `$ make watch`).

The issues can also be browsed here: https://scrutinizer-ci.com/g/jacebrowning/doorstop/issues/develop

**Comment by jmacarthur** [comment]
Hi, I'm going through some of these now; should have a patch soon.

**Comment by jacebrowning** [comment]
I'm going to chip away at a few as well.

**Comment by jacebrowning** [comment]
When this is done, we'll want to update the CII status: https://bestpractices.coreinfrastructure.org/projects/754#quality

**Comment by jacebrowning** [comment]
I updated the CII status to indicate that all warnings are addressed.

**Comment by devcurmudgeon** [comment]
w00t! :)
