### ISSUE TITLE
Assets missing when publishing single document

### ISSUE THREAD

**Issue by blastur** [jacebrowning/doorstop#257]
If I publish all my documents to HTML, e.g

`$ doorstop publish all ./html`

Doorstop will automatically copy assets into the output directory. If I only publish a single document, e.g

`$ doorstop publish REQ ./html/req.html`

.. no assets are copied into the output directory, which will cause the document to render incorrectly and should be considered broken.

Steps to reproduce:
1. Publish a single document with the default template
2. Note neither bootstrap.min.css nor sidebar.css are copied to the destination dir, but referenced from the default template.

**Comment by blastur** [comment]
Seems like the assets are copied, but for some reason the page just looks different (no links to each chapter in the sidebar). So this is probably a non-issue!

**Comment by michaelnt** [comment]
The sidebar navigation is broken when publishing a single file as the links are missing

**Comment by jmacarthur** [comment]
It's a check in publisher.publish:
    
    `linkify = is_tree(obj) and ext in ['.html', '.md']`

Removing the is_tree check will make links appear in a single document. Was there a reason for this - maybe to make it more readable as a printed document?

**Comment by jacebrowning** [comment]
Is this still an issue? It's the last bug to go before the v1.3 release is ready to go out.
