### ISSUE TITLE
Example documents

### ISSUE THREAD

**Issue by jmacarthur** [jacebrowning/doorstop#263]
It would be good to have some example requirements - ones that aren't requirements of requirement management tools, since that can be confusing. Does anyone know of any permissively licenced requirements documents for real projects? I'd be happy to do the conversion.

**Comment by devcurmudgeon** [comment]
I'm guessing the generic [Trustable Software Requirements](http://mustard.trustable.io/trustable-mustard/HEAD/requirements) are too simplistic so far?

Alternatively maybe we could encourage or work with Niall on his [iota](https://lists.trustable.io/pipermail/trustable-software/2017-March/000207.html) requirements?

**Comment by jmacarthur** [comment]
They're not too simple, but they're about specifying requirements; it's too meta. Iota might work.

**Comment by devcurmudgeon** [comment]
Ok, well another idea would be to map the NIST or other OpenControl standards...

**Comment by jacebrowning** [comment]
What if we reimplemented a basic unix utility (such as `cat`), but followed a strict requirements process? Would that be a worthwhile example?

**Comment by jacebrowning** [comment]
There is a call-to-action on this page to add open source examples: https://doorstop.readthedocs.io/en/latest/examples/

I think that's sufficient for now.
