### ISSUE TITLE
Changes to Derived and Normative attributes in XLSX are lost when importing.

### ISSUE THREAD

**Issue by MartyLake** [jacebrowning/doorstop#266]
Steps to reproduce:

1. create some SDD and SRD
2. `$ doorstop export -x all export`
3. modify Derived and/or Normative attributes in XLSX to TRUE (step3)
4. `$ doorstop import export/SDD.xlsx SDD && doorstop import export/SRD.xlsx SRD && doorstop export -x all export`

What I see:

- all Derived and Normative attributes are set to FALSE

What I expect:

- all Derived and Normative attributes are the same as (step3).

--------------------

I'm new to requirements management, so I may have missed something fundamental (two days ago I was still trying to make sense of these attributes).

Best,

**Comment by jacebrowning** [comment]
Thanks for the clear bug report. I haven't tried to reproduce this myself, but I'd image it's an issue with the boolean type in Excel not getting translated to Python.

What version of Excel are you using?

**Comment by MartyLake** [comment]
I'm using libre office updated last week.

If I recall correctly, It prompts me something like "=TRUE()" Or "=FALSE()"
when editing the cell. I just copied the true value from the Active
attribute to the Derived attribute thinking that it would be OK.

Le 6 avr. 2017 8:07 PM, "Jace Browning" <notifications@github.com> a écrit :

Thanks for the clear bug report. I haven't tried to reproduce this myself,
but I'd image it's an issue with the boolean type in Excel not getting
translated to Python.

What version of Excel are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jacebrowning/doorstop/issues/266#issuecomment-292259175>,
or mute the thread

**Comment by jacebrowning** [comment]
Would you be able to attach the XLSX file to this issue (with your sensitive information redacted)?

**Comment by MartyLake** [comment]
More infos about Libre Office

Version: 5.3.1.2 (x64)
Build ID: e80a0e0fd1875e1696614d24c32df0f95f03deb2
CPU Threads: 4; OS Version: Windows 6.19; UI Render: default; Layout Engine: new; 
Locale: fr-FR (fr_FR); Calc: group

I've redacted out any sensitive information of the exported XLSX and attached them. When doing the export-edit-import, "normative" and "derived" columns is always equal to "=FALSE()", and active is always equal to "=TRUE()". I copied the "true" cell from the active column to the derived columns (SDD1-5). If I import-export, there value is reset to "=FALSE()".

[SDD bugreport.xlsx](https://github.com/jacebrowning/doorstop/files/910055/SDD.bugreport.xlsx)
[SRD bugreport.xlsx](https://github.com/jacebrowning/doorstop/files/910054/SRD.bugreport.xlsx)

**Comment by michaelnt** [comment]
When I export an xlsx and open it in excel I see the derived column contains the strings "TRUE" or "FALSE". In the attached xlsx I see them set to the formula =TRUE() which displays as 0 or 1. So I think this is related to the use of LibreOffice. 

Seems like there isn't any checking on the values of attributes in the [importer](https://github.com/jacebrowning/doorstop/blob/develop/doorstop/core/importer.py#L263)
