### ISSUE TITLE
How can you associate tests with requirements?

### ISSUE THREAD

**Issue by michaelnt** [jacebrowning/doorstop#271]
I'd like to know that all of the requirements are tested, by for example a set of unittests,  py.test, pytest-bdd etc. Is there anyway that doorstop can help with that?

The ref field allows me to manually specify the tests for each requirement but there is no requirement for an item to have a ref. I was wondering about having a tag in the tests, e.g. HL001, and having doorstop search for those?

**Comment by jacebrowning** [comment]
As you mentioned, this is the intended purpose of the `ref` field on items.

> but there is no requirement for an item to have a ref

Either way you're going to need to review your test coverage manually. Part the review process for your `HL` and `HLT` documents should include:

- confirm that each `HL` item is covered by enough tests (`HLT`)
- confirm that each `HLT` item points to an automated test
- confirm that each automated test correctly implements the `HLT`

**Comment by michaelnt** [comment]
Thanks, we're going to try embedding our pytest-bdd feature files in the HLTs. I've a script that exports the features from the HLTs by looking for code sections in the markdown.
