### ISSUE TITLE
Error: multiple root documents

### ISSUE THREAD

**Issue by EzraIsReal** [jacebrowning/doorstop#293]
Hi I've been trying to figure doorstop out for the past couple of days, but the documentation doesn't cover the problems I've encountered, so I just need help figuring this issue out: it seems that I cannot execute any commands because of multiple root documents, how do I go about fixing that?

**Comment by nikhilsharma5** [comment]
I am facing same problem @jacebrowning. For me, it happens when I tried adding more requirements after a couple of days and it just starts throwing "multiple root documents".

**Comment by jacebrowning** [comment]
What is `mvn`?

I'm not sure how to help without more information. What was the output of `$ doorstop -v`?

**Comment by nikhilsharma5** [comment]
@jacebrowning this issue was resolved after running mvn clean. Thank you for quick reply tho 👍

**Comment by jacebrowning** [comment]
Good to know.

**Comment by manojmsrit** [comment]
**Getting error "Multiple Root documents"**

Below is the output for the "doorstop -v" command.

(base) MANOJs-MacBook-Air:doorstop manojdeshpande$ doorstop -v
looking for documents in /Users/manojdeshpande...
found document: SRD
found document: SRD
found document: HLTC.txt
found document: HLTC
found document: REQ
found document: TUT
found document: LLT
found document: HLT
found document: SRD
found document: TST
building tree...
root of the tree: SRD
root of the tree: SRD
ERROR: multiple root documents

How to delete the documents and re create new one's

(base) MANOJs-MacBook-Air:doorstop manojdeshpande$ doorstop create MNQ --parent SRD .
building tree...
ERROR: multiple root documents

(base) MANOJs-MacBook-Air:doorstop manojdeshpande$ doorstop delete SRD
building tree...
ERROR: multiple root documents
