### ISSUE TITLE
ISO 26262 and IEC 61508 Certification.

### ISSUE THREAD

**Issue by jed-frey** [jacebrowning/doorstop#297]
Bounty: https://www.bountysource.com/issues/58076160-iso-26262-and-iec-61508-certification

**Comment by zoek1** [comment]
@jed-frey can you describe more about this or at least what is the acceptance criteria or you definition of done?

**Comment by jed-frey** [comment]
A ```doorstop``` equivalent to [Rational DOORS kit for ISO 26262 and IEC 61508](http://www-01.ibm.com/support/docview.wss?uid=swg21617906)

Up to debate and discussion on what that *means*:

- A fancy piece of paper from governing bodies on how ```doorstop``` meets the certifications.
- A white paper from a respected corporation on how ```doorstop``` was used to meet certifications.
- A logical argument, accepted by [redacted] management, as to why DOORS and DOORS NG are irrelevant in meeting certification.

**Comment by bastiedotorg** [comment]
Hi,
generally - first of all we have to do a Tool Classification acc. ISO 26262.
Therefore we will check Tool Impact and Tool Detection.

TI:
Could the tool violate a safety requirement
-> I'd say yes (requirement could be dropped)

TD:
Can the tool detect errors? -> Possible Answers: high, medium, low, not present.
Here we should check the combination of git and doorstep.
I'd argue that git is fine (many people use it, correct version management and manual should cover that)
So we should put focus on if doorstep could ignore files within a folder.
And how doorstep acts with garbage data and maybe with text formatting.

If we have the answer here and can say "high error detection", we are just facing Tool Confidence Level (TCL) 1 - which is basically correct config management and manual in place. (no source code checking whatsoever)

**Comment by jacebrowning** [comment]
This seems sufficient to me.
