### ISSUE TITLE
first item in a level (level: 1.0) gets formatted differently from the rest (level: 1.1, 1.2, etc.) when `door publish`

### ISSUE THREAD

**Issue by iamhuzhe-microleads** [jacebrowning/doorstop#304]
Is this intentional, that when `door add REQ` three times, then `door publish REQ doc.html` or `door publish REQ doc.md`

The first item is one level up than the rest. 

It can be traced back to the `def _format_level(level):` function inside `publisher.py` where

    def _format_level(level):
    """Convert a level to a string and keep zeros if not a top level."""
    text = str(level)
    if text.endswith('.0') and len(text) > 3:
        text = text[:-2]
    return text

So `level: 1.0` the ending zero was thrown out. 

Is there a reason for that? Prettier document or a traditional style?

**Comment by iamhuzhe-microleads** [comment]
I see from the example document. `n.0` is used as title of the whole section, that's probably why it's one level higher than the rest.

**Comment by jacebrowning** [comment]
Yeah, this is intentional, the first item is the heading for the document.

**Comment by iamhuzhe-microleads** [comment]
Yes, it's mentioned in the document. A small inconsistency though: 

the level x.0 item, its `normative` field is still `true`, instead of `false`

**Comment by jacebrowning** [comment]
Yes, the first heading should be `normative=False`. Thanks for the report!

**Comment by RomainTT** [comment]
So what is the expected behaviour here ? Not to level up the heading of 1.0 if it is normative (with the risk of not having any heading in that case) or **force** to have a `normative=false` as the first item ?

**Comment by jacebrowning** [comment]
I think we should set `normative=false` on the heading item the moment an item is added under it.

**Comment by RomainTT** [comment]
That kind of forces the user to write a heading for its section, whether he wants or not. I don’t say it’s a bad idea. But is it really problematic to have sections without heading ?

**Comment by jacebrowning** [comment]
I can also see the case for leaving this behavior as-is. It's mostly there to introduce new users to the concept of headings otherwise someone will quickly end up with `1.0, 2.0, 3.0, ...` and have to do a fair about of work to restructure their document.

**Comment by RomainTT** [comment]
Does it mean that an item ending with `.0` should not be normative, and only used as a heading? (I am trying to understand how it works)

**Comment by jacebrowning** [comment]
Yes: https://github.com/jacebrowning/doorstop/blob/e24fc2b44627441be5e40ff994e5e9da46588b34/doorstop/core/types.py#L304-L306

If I were to build this again I think I would have made `heading` more explicit, but that's how it works today. 😄

**Comment by RomainTT** [comment]
Ok so I suggest only a small update of the documentation in that case :smile: just to make things clearer.

**Comment by jacebrowning** [comment]
I'm going to say this is working as intended for now.

**Comment by danieleades** [comment]
this is very surprising behaviour
