### ISSUE TITLE
edit command requires --tool option. Support for $EDITOR from environment?

### ISSUE THREAD

**Issue by aars** [jacebrowning/doorstop#315]
There are several mentions of 'default editor' in the code and tests. The edit command however requires `-T/--tool/` flag, so no default editor can even be considered here.

This tutorial item then, does not work:
https://github.com/jacebrowning/doorstop/blob/0353d4bd3d5cc138895025c32018d02937a4d4e4/reqs/tutorial/TUT001.yml

Since running `doorstop edit` will invariably exit with:
`doorstop edit: error: the following arguments are required: -T/--tool`

This is something that this test _is_ aware of though. 
https://github.com/jacebrowning/doorstop/blob/0353d4bd3d5cc138895025c32018d02937a4d4e4/doorstop/cli/tests/test_tutorial.py

Regression?

**Comment by jacebrowning** [comment]
Yes, I think this behavior must have regressed when the `--tool` option was added long ago.

Maybe we should remove `--tool` in favor of `$EDITOR`?

**Comment by aars** [comment]
I would be in favour of `$EDITOR`, since it is a common strategy. But I don't know what type of users doorstop has, and if removing something explicit like `--tool` in favour of something implicit would negatively affect their experience or learning curve. I think if we ensure `$EDITOR` is mentioned in the `--help` output and documentation we should be fine.

**Comment by aars** [comment]
I'll make a PR for this.

**Comment by aars** [comment]
https://github.com/jacebrowning/doorstop/pull/316
