### ISSUE TITLE
Content (Attributes) of yaml files is hard-coded

### ISSUE THREAD

**Issue by JensWalther** [jacebrowning/doorstop#319]
Shoudn't there be a configuration to select the parameters of a Requirement?

Currently in item.py the parameters are hard-coded:

       # Set default values
        self._data['level'] = Item.DEFAULT_LEVEL
        self._data['active'] = Item.DEFAULT_ACTIVE
        self._data['normative'] = Item.DEFAULT_NORMATIVE
        self._data['derived'] = Item.DEFAULT_DERIVED
        self._data['reviewed'] = Item.DEFAULT_REVIEWED
        self._data['text'] = Item.DEFAULT_TEXT
        self._data['ref'] = Item.DEFAULT_REF
        self._data['links'] = set()

**Comment by jacebrowning** [comment]
We have tried to include parameters that should work for most projects. Which ones do not apply to your project?

**Comment by JensWalther** [comment]
In our DOORS we have e.g. these parameters:
    Additional Information  
    Verification Criteria # Input for the test spec
    Rationale # High level context
    Functional Type # Funtional vs. non-functional vs. interface
    Relevance # Archtiecture vs. Desgin vs. Code
    Impact # Performance vs. Startup vs. Memory,...


How could I insert them in the yamls?

**Comment by jacebrowning** [comment]
> Functional Type # Funtional vs. non-functional vs. interface

`normative=True` is intended to be for functional requirements.

> Relevance # Archtiecture vs. Desgin vs. Code

This could be part of the `heading` or just different sections of the document.

> Verification Criteria # Input for the test spec
> Rationale # High level context
> Impact # Performance vs. Startup vs. Memory,...

I would place the rest of this information in `text` as it's not semantically parseable by this tool.

**Comment by JustinW80** [comment]
You could also just add them as key-value pairs in each item. See the [item reference documentation](https://doorstop.readthedocs.io/en/latest/reference/items/).

For the example item:

```
active: true
derived: false
level: 2.1
normative: true
reviewed: 1f33605bbc5d1a39c9a6441b91389e88
links: []
ref: ''
text: |
  Doorstop **shall** provide unique and permanent identifiers to linkable
  sections of text.
```
Add some lines like these:
```
verification: demonstration
rationale: 'Change Request xyz'
impact: reliability
```
