### ISSUE TITLE
Automated test execution report ?

### ISSUE THREAD

**Issue by RomainTT** [jacebrowning/doorstop#320]
Hello ! This is just a question.

I wonder if there is already something which generates a detailed report of a "test plan".

For instance, to validate a merge-request I want to run tests 01, 02, 03. Something went wrong with test 02 and I want to write manually what I observed. In this situation, is there anything to create a document (html for instance) detailing my "test plan" with its title, its description, the list of tests and their content, and the actual result they got ?

If that is not included in doorstep I am thinking about creating my own tool that would use doorstep to retrieve info.

**Comment by jacebrowning** [comment]
You could create one Doorstop document for the test plans and another for the test results -- linking each result report to the test plan item that was run.

But I probably would try to leave results data outside of Doorstop and connect the two using some custom scripting.

**Comment by jacebrowning** [comment]
> A simple comment indicating the IDs of the tests for instance?

Yeah, that would work. Maybe store this in a machine-parseable format so you can later use this list of IDs to query Doorstop through some scripts?
