### ISSUE TITLE
Drop support for Python 3.4

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/doorstop#324]
Python 3.4 won't be maintained after March 2019 (PEP 429).

**Comment by sebhub** [comment]
Documentation mentions Python 3.4+:

https://doorstop.readthedocs.io/en/latest/#setup

**Comment by jacebrowning** [comment]
Thanks for pointing that out!

Fixed in https://github.com/jacebrowning/doorstop/commit/a92a1520e92f5a55774c02fbd4ffd58ca6bc5909
