### ISSUE TITLE
Feature Proposal: Math Expressions in LaTeX syntax

### ISSUE THREAD

**Issue by tangoalx** [jacebrowning/doorstop#332]
It would be great, if it is possible to write math expressions in LaTeX syntax in the `text` attribute of an item and also if this expression is rendered  in HTML.

- I propose the usage of the package `python-markdown-math` for parsing of LaTeX code in `text` attribute. That package extends the already used `Markdown` package. 
- Render in HTML can be solved by the wide-spread javascript library MathJax.

Note: MathJax is quite a big javascript collection which should be avoided to be added directly to the repository of doorstop.

**Comment by jacebrowning** [comment]
Added in https://github.com/jacebrowning/doorstop/pull/334
