### ISSUE TITLE
Feature Proposal: Render PlantUML diagrams

### ISSUE THREAD

**Issue by tangoalx** [jacebrowning/doorstop#335]
Imagine an item `OBL010.yml`:
```
    active: true
    derived: false
    level: 1.2.3.1
    links: []
    normative: true
    ref: ''
    reviewed: null
    text: |
      Cyclic Program Activation

      ```plantuml
      @startuml
      [*] -right-> idle
      idle -right-> fetch : new cycle event
      fetch -down-> process : queue is empty
      process -left-> output : precess finished
      output -up-> idle : output stable
      @enduml
      ```    
```
This shall be rendered as follows:
![plantuml-integration-proposal](https://user-images.githubusercontent.com/46009720/58762806-da22bc00-8553-11e9-9a1e-73ef850cd5d7.png)

This can be achieved by using [PlantUML](http://plantuml.com/de/index), a textual description format for diverse diagram types like `Sequence Diagram`, `Class Diagram`, `Activity Diagram`, `State Chart Diagram` and many more. 

Fortunately, we can integrate this feature with the python package [plantuml](https://pypi.org/project/plantuml/), which works together with a public [plantuml server](http://www.plantuml.com/plantuml/img/). That plantuml server processes the textual input and renders it into a downloadable image, which we can store in the `assets` folder of a publication (don't rely that the image will be available on the server forever).

Note also, that the python package [plantuml](https://pypi.org/project/plantuml/) already allows to redirect your plantuml code to an own plantuml server and let it render your diagrams instead of rendering it on a public server. This could be interesting for companies. Therefore, the server address shall optionally be overridden by an argument to doorstop.

Of course it would be possible to keep the `plantuml code` apart of the doorstop items and just link the image into the item. However, this does not feel natural and has some drawbacks:
- as author, you need to keep the item and the plantuml code in sync, which is more complicated, because they are not in the same file
- changing the image would not lead to `suspected` status automatically
- if you want to get the `suspected` status when changing the image, then you need to change the link address, so the file name of your generated plantuml image must always change. This seems fragile and may lead to invalid links.

**Comment by JustinW80** [comment]
I've been pitching Doorstop to my team for requirements while also boosting PlantUML alongside in design description documents. Integrating PlantUML in Doorstop's text field would be a big win for our use case.

**Comment by tangoalx** [comment]
Glad to hear that this feature will serve somebody else, too!

I've made a draft version here: 80206fe1431165260a7b62f058d1d2416914e2dd

It uses [plantuml-markdown](https://github.com/mikitex70/plantuml-markdown). Plantuml must either be installed locally or as a server as described on the plantuml-markdown page. I installed it [locally](https://github.com/mikitex70/plantuml-markdown). Note also that plantuml-markdown offers further attributes like `format`, `height`, `width`, `classes`, `alt`, `title` to control the export of the diagram.

The images are not saved in the assets directory, instead they are inserted as html inline data. For me that is also ok. It is possible to export the image with your browser.

I will need some time to integrate that in the test environment. It also would be nice, if we extend the requirements to `doorstop` and also the manual by such a feature.

**Comment by tangoalx** [comment]
@JustinW80: By the way, I think that it has already been possible to use plantuml inside the text attribute and then export to markdown format. Then you can use `pandoc` to convert to any format like PDF or HTML while PlantUml is rendered. Same for MathLatex or other stuff. Anyway, I prefer to be directly integrated.

**Comment by jacebrowning** [comment]
We support this now: http://jacebrowning.github.io/doorstop/TUT.html#TUT017
