### ISSUE TITLE
Optionally add extended attributes to fingerprint

### ISSUE THREAD

**Issue by sebhub** [jacebrowning/doorstop#337]
Currently, the [extended attributes](https://doorstop.readthedocs.io/en/latest/reference/items/#extended-attributes) are not covered by the fingerprint used by the [doorstop review](https://doorstop.readthedocs.io/en/latest/reference/items/#reviewed). It should be possible to place also extended attributes under the fingerprint scope. One way to do this could be via the `.doorstop.yml` document configuration file:
```yaml
settings:
  digits: 3
  prefix: X
  sep: ''
  reviewed: [a, b, c]
  optional: [a]
```
The `reviewed` and `optional` are new optional document configuration options.

Values in `reviewed` name extended attributes which should be placed under the fingerprint scope in this order after the standard attributes.

Values in `optional` name extended attributes which are optional, e.g. in case an extended attribute is not found in the item file no error is reported, otherwise an error is reported.

Would such a feature be acceptable?

I have some implementation remarks.

The Item.stamp() methods needs to be extended to also cover the extended attributes which are configured to be under the fingerprint scope:
https://github.com/jacebrowning/doorstop/blob/569a24eb42423708adeed4e17a19188a8e733e56/doorstop/core/item.py#L860-L866

I am not sure how I can get in an Item method to the corresponding instance of the Document class?

**Comment by jacebrowning** [comment]
I think both of these features could be useful. These might be easier to review as separate PRs.

> I am not sure how I can get in an Item method to the corresponding instance of the Document class?

Is `self.document` available in that context?

**Comment by sebhub** [comment]
With separate features you mean the reviewed configuration option is one and the other is the optional configuration option?

**Comment by jacebrowning** [comment]
Yes.

**Comment by sebhub** [comment]
Ok, good we try to write a patch for the reviewed configuration option and raise an error if it is not present in the item file.

**Comment by sebhub** [comment]
We want to use item.document in the stamp() member function. If we don't check for item.document we get AttributeError exceptions in the test suite:
```
ERROR: Verify new items are cached.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/EB/ting_p/Tests/doorstop/doorstop/core/tests/test_item.py", line 576, in test_new_cache
    level=(1, 2, 3))
  File "/home/EB/ting_p/Tests/doorstop/doorstop/core/base.py", line 20, in wrapped
    item = func(self, *args, **kwargs) or self
  File "/home/EB/ting_p/Tests/doorstop/doorstop/core/item.py", line 149, in new
    for i in item.document.extended_reviewed:
AttributeError: 'NoneType' object has no attribute 'extended_reviewed'
```
Are there real world use cases in which an Item() object has no associated document or do we have to just fix the test suite to provide a mock document?

**Comment by jacebrowning** [comment]
I don't think there are real work cases where that can happen -- I believe `document` is `None` for item unit tests.

Maybe `stamp()` should only look for extended attributes when `self.document` exists? I think we'll also want at least once case where `self.document` is a mock to test fingerprinting extended attributes.

**Comment by sebhub** [comment]
> I don't think there are real work cases where that can happen -- I believe `document` is `None` for item unit tests.
> 
> Maybe `stamp()` should only look for extended attributes when `self.document` exists?

We currently have an "if self.document:" in this method, however, if you think that normally an Item is has a corresponding Document, then I think it is better to remove the if statement, add an @requires_document and adjust the test suite to use Document mocks.

> I think we'll also want at least once case where `self.document` is a mock to test fingerprinting extended attributes.

Yes, we will add test cases for the new feature.

**Comment by RomainTT** [comment]
Do you think this feature is compatible with my suggestion in #330 ? Personally, I think so. A field like `template` could be placed alongside `extended-reviewed`

**Comment by sebhub** [comment]
Yes, I think this feature is compatible with #330. In the pull request #340 we have a problematic area:

https://github.com/jacebrowning/doorstop/pull/340/commits/8dd540336f716404b96f226cf1f31479e1fce393#diff-df3c98ba20e3a4a7be5b82aebf509681R486

The init_reviewed_extended_attributes() does a best effort approach. It initializes the reviewed extended attributes with an empty string. This is not really good, since the layer doesn't know if an empty string is something good. It would be better to use a template based approach for this.

**Comment by sebhub** [comment]
I just noticed that this issue is a duplicate of #134.
