### ISSUE TITLE
Cycles via links produce no warnings

### ISSUE THREAD

**Issue by sebhub** [jacebrowning/doorstop#342]
It is possible to create a cycle via the requirement links:

```
doorstop create REQ .
doorstop add REQ
doorstop add REQ
doorstop link REQ001 REQ002
doorstop link REQ002 REQ001
```
No warning for this circle is issued:
```
doorstop
building tree...
loading documents...
validating items...
WARNING: REQ: REQ001: no text
WARNING: REQ: REQ001: unreviewed changes
WARNING: REQ: REQ002: no text
WARNING: REQ: REQ002: unreviewed changes
```

**Comment by jacebrowning** [comment]
I think the best option will be to prevent the tree from building in the first place.

**Comment by sebhub** [comment]
I think the "doorstop link" which creates a circle should stop with an error and not modify anything. For people which edit the *.yml files by hand the "doorstop" invocation should issue a warning if there are circles present. I don't know if a circle detection is already there.

**Comment by jacebrowning** [comment]
That all sounds good to me. There is no cyclic link detection currently in place.

**Comment by sebhub** [comment]
I am a bit concerned if this feature could end up in a performance problem. I have to figure out which data structures are already built up. Is there a directed graph of all items?

**Comment by sebhub** [comment]
Checking for cycles in an existing tree and issue warning for all cycles probably we have modify
```
    def get_issues(self, skip=None, document_hook=None, item_hook=None):
        """Yield all the tree's issues.
```
in tree.py. A standard algorithm to detect cycles in a directed graph should be used.

**Comment by jacebrowning** [comment]
Closed by https://github.com/jacebrowning/doorstop/pull/343
