### ISSUE TITLE
Verify an item has upward links not correctly implemented

### ISSUE THREAD

**Issue by sebhub** [jacebrowning/doorstop#345]
The document validation should verify an item has upward links with this code fragment (item.py):
```python
        # Verify an item has upward links
        if all((document.parent,
                self.normative,
                not self.derived)) and not self.links:
            msg = "no links to parent document: {}".format(document.parent)
            yield DoorstopWarning(msg)
```
This test is insufficient, since an item may have document internal links to pass this test.

**Comment by jacebrowning** [comment]
I understand what you're getting at, but at some point it's the responsibility of the reviewer to ensure all links are actually valid. I think this code was originally added simply to serve as a reminder to the author that a new item still needs to be linked.

What is your proposed improvement to this check?

**Comment by sebhub** [comment]
I try currently to understand how doorstop works, since I have to write some documentation for our project (RTEMS). The doorstop documentation for the [validation](https://github.com/jacebrowning/doorstop/blob/develop/docs/cli/validation.md) is not very detailed. My aim is to document the conditions which cause info, warning and error messages. For this I have to review he code and noticed that in this area comment and code do not harmonize. My proposal is this:

For normative, derived items in all documents (also the top level document) the links set should be non-empty.

Normative, non-derived items in child documents (a document.parent exists) a link to an item of the parent document should exist. I am not sure if this should be weakened to: .. a link to an item of an arbitrary ancestor (e.g. parent) document should exist.

**Comment by jacebrowning** [comment]
That sounds reasonable to me. I'd love some help with the documentation here!

**Comment by sebhub** [comment]
Now I think the code is fine, since some lines below an info is generated if a link is not to an item in the parent document. However, the comments should be changed.
