### ISSUE TITLE
MD5 as a stamp algo

### ISSUE THREAD

**Issue by stefanoco** [jacebrowning/doorstop#358]
I'm new to doorstop and find it very interesting. I'm a bit concerned about the fact that fingerprinting as per Stamp class implementation here:

https://github.com/jacebrowning/doorstop/blob/5f624c80f81c950fedc30af34852979b67d57597/doorstop/core/types.py#L508) 

is still using MD5 hashing algorithm. Apart from being deprecated since long ago for any cryptography use (which is not the case here) it's also something not easily found on any modern application. Git itself is using SHA1 for creating hashes, and I suspect any expert body reviewing doorstop would regard using MD5 as suspicious as a minimum. Collision is not far from happening, and mangling for causing collision is also possible. Before the develpment goes too far would it be a good idea to (1) switch to SHA1 and (2) include a reference to the used algorithm in each hash so that any future change would not break compatibility?

**Comment by sebhub** [comment]
This was also one of the first things I noticed during a review of the code base. I guess, MD5 raises a red flag for most reviewers with a security background. In Doorstop, the fingerprint hash should just detect if something changed and a review is required. For this purpose MD5 is sufficient. To avoid questions it may make sense to make the hash algorithm configurable with a document setting (.doorstop.yml), e.g.
```yaml
settings:
  stamp-algorithm: sha512
```
Items could use a self.document.stamp() method to do the stamping.

**Comment by stefanoco** [comment]
Sounds good for me. Correct to say that MD5 is sufficient for text files change detect, but I'm concerned about the possibility that having custom fields included in the MD5 check sometimes in the future more complex data is also subject to hashing (pictures?) and chances for a collision get high

**Comment by sebhub** [comment]
The fingerprint just needs to cover random content changes. For this MD5 is fine.

**Comment by jacebrowning** [comment]
I agree and I don't think there's a need for the algorithm to be customizable.

**Comment by sebhub** [comment]
Sorry, I have to reopen this issue, since I have now a use case for a cryptographically secure hash algorithm. Suppose that your requirements must go though a change control board (CCB). Members of the CCB will review and approve your requirements. They can do the approval with a [digital signature](https://en.wikipedia.org/wiki/Pretty_Good_Privacy#Digital_signatures) of a cryptographically secure fingerprint of the item (message). In this scenario MD5 is insufficient.

**Comment by sebhub** [comment]
I have to think more about the CCB workflow. The usage of the fingerprint alone is probably a bit cumbersome and maybe also insecure.
