### ISSUE TITLE
ReqIF requirements exchange format

### ISSUE THREAD

**Issue by stefanoco** [jacebrowning/doorstop#361]
[ReqIF(https://www.omg.org/spec/ReqIF/About-ReqIF/) is today a common exchange format for requirements (XML dialect), with more details than a plain CSV and recognized by several different tools.

Not a big deal perhaps for exchanging between some other requirements management tool and Doorstop, but potentially pretty useful when exchanging requirements between Doorstep and test cases management (Cantata and similar).

Am I the only one feeling this would be useful?

**Comment by jacebrowning** [comment]
The rationale for closing an [older issue](https://github.com/jacebrowning/doorstop/issues/104#issuecomment-395424927) was that most tools can export in XLSX which should transfer all required metadata into Doorstop. But if there is a tool that only exports ReqIF maybe it's worth adding an [importer function](https://github.com/jacebrowning/doorstop/blob/develop/doorstop/core/importer.py) for that format.

**Comment by stefanoco** [comment]
Actually you're correct it seems that XLSX/CSV cover well all needs, sorry for not having noticed the past issue.

**Comment by fkromer** [comment]
Sorry for commenting this old issue. But isn’t  the issue with XLSX and CSV that it is not standardized as ReqIf is? I‘d expect that every other tool is able to import and export ReqIf.
