### ISSUE TITLE
`header` field is not imported from xlsx

### ISSUE THREAD

**Issue by sevendays** [jacebrowning/doorstop#379]
**Steps to reproduce:**

* create a couple requirements in Excel, `reqs.xlsx`
* add the column "header"
* fill in the headers for each requirement
* run `doorstop import REQS reqs.xlsx`

**Expected outcome:**

* Requirements have the `header` YAML field

**Actual outcome:**

* Requirements don't have the `header` YAML field

**Additional info**

* Custom fields, like `summary` instead of `header`, work flawlessly.
* doorstop 1.5 
* python 3.7.3 64 bit on windows 10
* excel version: microsoft office 365 business, version1906

**Comment by michaelnt** [comment]
At the moment you need to add the -b header option. 

Your don't need to do that in the latest beta or development versions

**Comment by sebhub** [comment]
This issue is fixed in the development branch. There is also a test case for this in the importer tests.
