### ISSUE TITLE
xlsx formula is parsed instead of the value

### ISSUE THREAD

**Issue by sevendays** [jacebrowning/doorstop#380]
**Steps to reproduce**

* write some requirements in excel
* add a `summary` custom column, e.g. `summary`
* write a formula in the first cell of the custom column, e.g. `=IF(I2=FALSE,"",CONCAT(A2, " ASIL ",G2))`
* drag the first cell for the whole column length, so it is populated
* import the requirement set in doorstop

**Expected outcome**

* the cell **value** appears in the custom field (was: `summary`)

**Actual outcome**

* a `=` sign appears instead.

**Remarks**

* There is an option in openpyxl to read the values of the spreadsheet, instead of reading the data (the formula, in this case): `wb = openpyxl.load_workbook(filename, data_only=True)`
* _might_ be related to https://github.com/jacebrowning/doorstop/issues/266

**Comment by jacebrowning** [comment]
Thanks for reporting! We'll also want to add a test for this.
