### ISSUE TITLE
Minor bug: "bad listbox index "": must be active"

### ISSUE THREAD

**Issue by stanislaw** [jacebrowning/doorstop#391]
When the `>> Unlink Item` button is pressed, I am seeing the following in the logs:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/Stanislaw/.pyenv/versions/3.7.4/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "doorstop/gui/main.py", line 170, in wrapped
    return func(self, *args, **kwargs)
  File "doorstop/gui/main.py", line 877, in unlink
    self.listbox_links.delete(index)
  File "/Users/Stanislaw/.pyenv/versions/3.7.4/lib/python3.7/tkinter/__init__.py", line 2791, in delete
    self.tk.call(self._w, 'delete', first, last)
_tkinter.TclError: bad listbox index "": must be active, anchor, end, @x,y, or a number
```

The app does not crash, so it seems to be a minor bug.

**Comment by Shreya-2707** [comment]
from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot
from tkinter import *
bot = ChatBot(" My ChatsBot")

conv= [ 'Hello' , 'Hi Dear' ,
        'Whats ur name', 'My name is Bot,created by shreya' ,
        'how are you' , 'I am fine',
        'Can you tell me the wheather ', 'sunny day']

bot.set_trainer(ListTrainer)
bot.train(conv)

main =Tk()
main.geometry("500x650")
main.title("my chat bot")

def ask_bot():
   query = (str(textF.get()))
   value = str((btn.get(ACTIVE)))
   print(value)
   answer = bot.get_response(query)
   mssge.insert(END , "you : " + query)
   print(type(answer))
   mssge.insert((END , "bot :" + str (answer)))
   textF.delete(0, END)

frame =Frame(main)
sc = Scrollbar(frame)
mssge =Listbox(frame , width =50 , height=15)

sc.pack(side=RIGHT , fill=Y )
mssge.pack(side=LEFT, fill =BOTH , pady=10)
frame.pack()

textF = Entry(main , font =("arial",17))
textF.pack(fill=X, pady = 9)
btn =Button(main , text="ask from bot", font=('times', 15), command = ask_bot)
btn.pack()

main.mainloop()




D:\PycharmProjects\chatting\venv\Scripts\python.exe D:/PycharmProjects/chatting/Chatss.py
D:\PycharmProjects\chatting\venv\lib\site-packages\chatterbot\storage\jsonfile.py:24: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  warnings.warn(
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python_3.8.2_64\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "D:/PycharmProjects/chatting/Chatss.py", line 38, in ask_bot
    mssge.insert((END , "bot :" + str (answer)))
  File "D:\Python_3.8.2_64\lib\tkinter\__init__.py", line 3192, in insert
    self.tk.call((self._w, 'insert', index) + elements)
_tkinter.TclError: bad listbox index "end {bot :Hi Dear}": must be active, anchor, end, @x,y, or a number
<class 'chatterbot.conversation.statement.Statement'>
   
Can anybody give me the solution....
